### ISSUE TITLE
ModIndex unclear naming choice 

### ISSUE THREAD

**Issue by jakemumu** [zanegolas/MTEC_498#2]
Nice working Zane! Code is looking great! You nailed the FM -- however you're treating the amplitude of the fm operator as ModIndex? 

To me it would be cleared to do: 

```
auto modulator = mModulatorSine.getNextSample();
modulator *= 3 (aka, "mod amount");

auto output = mOutputSide.getNextSample(modulator);
```

I believe this is a bit clearer, you can scale your modulator signal before it goes into the function and sums against the phase.

**Comment by zanegolas** [comment]
This should be fixed in pull request #3
